# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('job_start_date', models.DateTimeField(verbose_name='Job start date')),
                ('job_finish_date', models.DateTimeField(verbose_name='Job finish date')),
                ('sign', models.ImageField(upload_to=b'')),
                ('stamp', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
