# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160318_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.ImageField(upload_to=b'')),
                ('stamp', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='actor',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='stamp',
        ),
        migrations.AlterField(
            model_name='organ',
            name='location',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='organ',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
