# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20160318_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job_finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Job finish date'),
        ),
    ]
