# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20160318_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='signet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Signet'),
        ),
    ]
