# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20160318_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('file', models.FileField(upload_to='docs/')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='signet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.Signet'),
        ),
        migrations.AlterField(
            model_name='signet',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='/signets/'),
        ),
        migrations.AlterField(
            model_name='signet',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='/signets/'),
        ),
        migrations.AddField(
            model_name='document',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Person'),
        ),
    ]
