# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20160318_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apostillerequest',
            old_name='Applicant',
            new_name='applicant_name',
        ),
    ]
