# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20160407_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apostillerequest',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='apostillerequest',
            name='department',
        ),
        migrations.AddField(
            model_name='apostillerequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.DepartmentUser'),
            preserve_default=False,
        ),
    ]
