# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 00:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20160407_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostillerequest',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 0, 8, 56, 9028), verbose_name='Application Date'),
        ),
    ]
