# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_auto_20160408_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostillerequest',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Application Date'),
        ),
    ]
