# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-21 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_auto_20160421_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.ImageField(default='/media//apostille.jpg', upload_to=b''),
        ),
    ]
