# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-21 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_department_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='icon',
        ),
        migrations.AddField(
            model_name='apostille',
            name='icon',
            field=models.ImageField(default='/media//apostille.jpg', upload_to=b''),
        ),
    ]
