# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-19 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_auto_20160429_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostillerequest',
            name='application_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Application Date'),
        ),
        migrations.AlterField(
            model_name='apostillerequest',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Approved'), ('r', 'Rejected')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='apostillerequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.DepartmentUser'),
        ),
    ]
